
version: '3'

services:
  laravel: 
    image: 'laradock/workspace:latest-7.4'
    volumes:
      - ./laravel-frontend:/var/www
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /var/www
    networks:
      - backend
    ports:
      - "80:8000"
    command: bash -c "tail -f /dev/null"
    entrypoint: /entrypoint.sh
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'mysql:8.0'
    volumes:
      - ./database/entry.sql:/docker-entrypoint-initdb.d/entry.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 20s

networks:
  backend: